"""Run report generator for shareable one-page performance briefs."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from contextwatch.monitor.advisor import Diagnosis, Finding, build_diagnosis
from contextwatch.monitor.forecaster import ForecastResult, compute_forecast


def generate_report_markdown(data: dict[str, Any], source_path: str) -> str:
    """Build a one-page markdown brief from a run log."""
    forecast = _get_or_build_forecast(data)
    diagnosis = _get_or_build_diagnosis(data, forecast)

    bottleneck = _primary_bottleneck(diagnosis)
    ts = data.get("timestamp", "unknown")
    mode = str(data.get("mode", "unknown")).upper()
    model = data.get("model", "unknown")
    generated = data.get("generated_token_count", 0)
    total = data.get("total_token_count", 0)
    context_summary = data.get("context_summary", {}) or {}
    latency_summary = data.get("latency_summary", {}) or {}
    memory_summary = data.get("memory_summary", {}) or {}

    lines: list[str] = []
    lines.append("# ContextWatch Performance Brief")
    lines.append("")
    lines.append(f"- Source log: `{source_path}`")
    lines.append(f"- Timestamp: `{ts}`")
    lines.append(f"- Mode: `{mode}`")
    lines.append(f"- Model: `{model}`")
    lines.append("")
    lines.append("## Executive Summary")
    lines.append(
        f"- Run status: **{diagnosis.status.upper()}** (`risk_score={diagnosis.risk_score}/100`)"
    )
    lines.append(f"- Primary bottleneck: **{bottleneck}**")
    lines.append(
        f"- Throughput snapshot: generated `{generated}` tokens (`{total}` total tokens in context)."
    )
    lines.append("")
    lines.append("## Key Metrics")
    lines.append(
        f"- Context used: `{_pct(context_summary.get('context_used_pct'))}` "
        f"({context_summary.get('final_total_tokens', 'n/a')}/{context_summary.get('max_context', 'n/a')})"
    )
    lines.append(f"- Remaining context tokens: `{context_summary.get('remaining_tokens', 'n/a')}`")
    lines.append(f"- TTFT: `{_fmt(latency_summary.get('ttft_ms'), 'ms')}`")
    lines.append(
        f"- Current token latency: `{_fmt(latency_summary.get('current_token_latency_ms'), 'ms')}`"
    )
    lines.append(
        f"- Latency trend: `{_fmt(latency_summary.get('trend_ms_per_100_tokens'), 'ms/100tok')}`"
    )
    if memory_summary:
        lines.append(f"- Current memory: `{_fmt(memory_summary.get('current_memory_mb'), 'MB')}`")
        lines.append(f"- Peak memory: `{_fmt(memory_summary.get('peak_memory_mb'), 'MB')}`")
    else:
        lines.append("- Current memory: `n/a` (server-managed or unavailable)")
    lines.append("")
    lines.append("## Forecast")
    lines.append(
        f"- Context saturation in: `{_fmt_int(forecast.tokens_until_context_limit, 'tokens')}`"
    )
    lines.append(
        f"- Memory limit in: `{_fmt_int(forecast.tokens_until_memory_limit, 'tokens')}`"
    )
    lines.append(
        f"- Latency threshold in: `{_fmt_int(forecast.tokens_until_latency_threshold, 'tokens')}`"
    )
    lines.append("")
    lines.append("## Findings")
    if diagnosis.findings:
        for finding in diagnosis.findings[:6]:
            lines.append(f"- [{finding.severity.upper()}] {finding.area}: {finding.message}")
    else:
        lines.append("- No active findings.")
    lines.append("")
    lines.append("## Recommended Actions")
    for idx, rec in enumerate(diagnosis.recommendations[:5], start=1):
        lines.append(f"{idx}. {rec}")
    lines.append("")
    lines.append(f"_Generated by ContextWatch report on {datetime.now().isoformat(timespec='seconds')}_")
    return "\n".join(lines) + "\n"


def default_report_path(log_path: str) -> str:
    """Return the default report path for a run log."""
    p = Path(log_path)
    return str(p.with_name(f"{p.stem}_brief.md"))


def _get_or_build_forecast(data: dict[str, Any]) -> ForecastResult:
    raw = data.get("forecast")
    if isinstance(raw, dict):
        return ForecastResult(
            tokens_until_context_limit=raw.get("tokens_until_context_limit"),
            context_already_saturated=bool(raw.get("context_already_saturated", False)),
            tokens_until_memory_limit=raw.get("tokens_until_memory_limit"),
            memory_already_exceeded=bool(raw.get("memory_already_exceeded", False)),
            memory_limit_mb=raw.get("memory_limit_mb"),
            tokens_until_latency_threshold=raw.get("tokens_until_latency_threshold"),
            latency_already_exceeded=bool(raw.get("latency_already_exceeded", False)),
            latency_threshold_ms=raw.get("latency_threshold_ms"),
        )

    ctx = data.get("context_summary", {}) or {}
    lat = data.get("latency_summary", {}) or {}
    mem = data.get("memory_summary", {}) or {}

    trend = lat.get("trend_ms_per_100_tokens")
    slope = (trend / 100.0) if isinstance(trend, (int, float)) else None

    return compute_forecast(
        total_tokens=int(data.get("total_token_count", 0) or 0),
        max_context=int(ctx.get("max_context", 0) or 0),
        current_memory_mb=mem.get("current_memory_mb"),
        avg_growth_per_token_mb=mem.get("avg_growth_per_token_mb"),
        memory_limit_mb=None,
        current_latency_ms=lat.get("current_token_latency_ms"),
        latency_slope_per_token_ms=slope,
        latency_threshold_ms=None,
    )


def _get_or_build_diagnosis(data: dict[str, Any], forecast: ForecastResult) -> Diagnosis:
    raw = data.get("diagnosis")
    if isinstance(raw, dict):
        findings = [
            Finding(
                area=str(item.get("area", "unknown")),
                severity=str(item.get("severity", "info")),
                message=str(item.get("message", "")),
            )
            for item in (raw.get("findings") or [])
        ]
        return Diagnosis(
            risk_score=int(raw.get("risk_score", 0) or 0),
            status=str(raw.get("status", "stable")),
            findings=findings,
            recommendations=[str(x) for x in (raw.get("recommendations") or [])],
        )

    ctx = data.get("context_summary", {}) or {}
    lat = data.get("latency_summary", {}) or {}
    return build_diagnosis(
        context_used_pct=ctx.get("context_used_pct"),
        latency_trend_ms_per_100_tokens=lat.get("trend_ms_per_100_tokens"),
        forecast=forecast,
        mode=str(data.get("mode", "hf")),
    )


def _primary_bottleneck(diagnosis: Diagnosis) -> str:
    weight = {"critical": 4, "high": 3, "medium": 2, "info": 1}
    areas = {"context": 0, "memory": 0, "latency": 0}
    for f in diagnosis.findings:
        if f.area in areas:
            areas[f.area] += weight.get(f.severity, 1)
    best = max(areas, key=areas.get)
    if areas[best] == 0:
        return "none detected"
    return best


def _fmt(value: Any, unit: str) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, (int, float)):
        return f"{value:.2f} {unit}"
    return str(value)


def _pct(value: Any) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, (int, float)):
        return f"{value * 100:.1f}%"
    return str(value)


def _fmt_int(value: Any, unit: str) -> str:
    if value is None:
        return "n/a"
    try:
        return f"{int(value)} {unit}"
    except Exception:
        return str(value)
